name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python_version: '3.11'
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y setuptools
          pip install git+https://github.com/kivy/python-for-android.git
          pip install cython requests
      - name: Build APK
        run: |
          p4a apk --private . \
            --package=com.gojo.filewatcher \
            --name="FileWatcher" \
            --version=1.0 \
            --bootstrap=sdl2 \
            --requirements=python3,kivy,requests \
            --arch=arm64-v8a \
            --permission INTERNET \
            --permission READ_EXTERNAL_STORAGE \
            --permission WRITE_EXTERNAL_STORAGE \
            --permission MANAGE_EXTERNAL_STORAGE \
            --service=Monitor:service.py
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FileWatcher-Build
          path: "*.apk"
